### ISSUE TITLE
Recaptcha2 support

### ISSUE THREAD

**Issue by martynassateika** [daylightstudio/FUEL-CMS-Forms-Module#13]
The forms module still uses Recaptcha v1, which is no longer supported. We should move to Recaptcha v2.

Information on how to set it up for PHP can be found at: https://github.com/google/recaptcha

I am going to try and implement the functionality. The question is what we do with Recaptcha 1? Should users still see it as an option when creating forms?

**Comment by martynassateika** [comment]
Note: there is also "Invisible ReCaptcha": https://developers.google.com/recaptcha/docs/invisible

**Comment by martynassateika** [comment]
I have a working Recaptcha2 widget in FUEL CMS :-)

@daylightstudio given that Google is dropping support for Recaptcha v1 in March 2018, do you reckon we just override the validation and rendering logic with that of v2's?

The next release of this module would just need a notice in the changes log about breaking changes (people would have to migrate their public/private Recaptcha keys).

**Comment by daylightstudio** [comment]
I think that would be best. Any chance you have a pull request for your work on the Recaptcha2 :)?

**Comment by martynassateika** [comment]
Yup I'll set one up as soon as I'm 100% done with it, hopefully today / tomorrow.

Thought maybe I should fix some existing bugs in separate PRs, e.g. there's #14.

**Comment by martynassateika** [comment]
Started up #15.
