### ISSUE TITLE
Special characters escaped in rendered form

### ISSUE THREAD

**Issue by martynassateika** [daylightstudio/FUEL-CMS-Forms-Module#18]
I have a website running FUEL CMS in a language that has some special characters, and that does not seem to play well with forms.

There is a form set up in the CMS. Some of its fields, as well as the "Submit" and "Reset" buttons, have labels with accented characters. As soon as the form is persisted, the characters become escaped. They're then rendered escaped in the form.

Is there any way to go around this without altering the code in the forms module?

**Comment by daylightstudio** [comment]
That is caused by the Forms_model.php $auto_encode_entities property which by default is set to TRUE. To properly overwrite it without editing the module's model, you can extend the model, overwrite the property and then in the fuel/application/config/MY_fuel_modules.php "module_overwrites" add the following:
```
$config['module_overwrites']['forms']['model'] = 'MY_forms_model';
```

**Comment by martynassateika** [comment]
Brilliant, didn't know about `module_overwrites`, thanks. I'll try this asap.

**Comment by martynassateika** [comment]
Hm, I tried it but it doesn't seem to work. Is the idea that the `initialize` method would be called by `Fuel_modules`?

It seems to get stuck here:

https://github.com/daylightstudio/FUEL-CMS/blob/58c0fc11f112628ef2c9f553cb5583bff0c2b866/fuel/modules/fuel/libraries/Fuel_modules.php#L205

**Comment by martynassateika** [comment]
Yeah, the line in `MY_fuel_modules` is:

```php
$config['module_overwrites']['forms']['model'] = 'MY_forms_model'; // Fix form labels not showing accented symbols
```

I also added a class `MY_forms_model` in `\fuel\application\models`:

```php
<?php if (!defined('BASEPATH')) exit('No direct script access allowed');
require_once(FUEL_PATH. 'models/Forms_model.php');

class MY_forms_model extends Forms_model {

	public $auto_encode_entities = FALSE;

	public function __construct()
	{
		parent::__construct();
	}

	public function initialize($table = NULL, $params = array())
	{
		parent::initialize($table, $params);
	}

}
```

The stack looks like this:

![settings](https://user-images.githubusercontent.com/3257241/37857352-40e498b4-2ef2-11e8-933c-c789b533cf8a.jpg)

**Comment by daylightstudio** [comment]
Sorry... try 'model_name' instead of 'model' as the key:
```
$config['module_overwrites']['forms']['model_name'] = 'MY_forms_model'; // Fix form labels not showing accented symbols
```

**Comment by martynassateika** [comment]
Thank you, that worked!

Do I need to be concerned about security after switching this flag?

**Comment by daylightstudio** [comment]
It only concerns encoding values on the model for forms which is only done in the CMS. It's better to have it but I don't see it causing much of an issue without it.

**Comment by martynassateika** [comment]
Ah yes. User data goes via the entries model. Great, looks like I'll keep it on then :-)
