### ISSUE TITLE
Only variables should be assigned by reference

### ISSUE THREAD

**Issue by ateebahmed** [daylightstudio/FUEL-CMS-Forms-Module#20]
I was developing a contact us form through cms and was to able to submit it. But after submitting it I got this error:
```
A PHP Error was encountered
Severity: Runtime Notice

Message: Only variables should be assigned by reference

Filename: libraries/Fuel_forms.php

Line Number: 754

Backtrace:

File: /Applications/MAMP/htdocs/nippa-tech/nippatech-cms/fuel/modules/forms/libraries/Fuel_forms.php
Line: 754
Function: _error_handler

File: /Applications/MAMP/htdocs/nippa-tech/nippatech-cms/fuel/modules/forms/controllers/Forms.php
Line: 23
Function: process

File: /Applications/MAMP/htdocs/nippa-tech/nippatech-cms/index.php
Line: 364
Function: require_once
```
Although I have turned on entries and the submitted data is available there. But this does not redirect me to the After submit text message. I tried switching javascript submission but still same error.
I tracked it down to line mentioned in trace:
`$model =& $this->CI->fuel->forms->model('form_entries');`
I tried removing it but this caused the page to redirect in a loop which browser stops after a while saying this page has redirected you too many times.

**Comment by daylightstudio** [comment]
This is fixed in the develop branch.
