### ISSUE TITLE
Create form field select options not working

### ISSUE THREAD

**Issue by sontq** [daylightstudio/FUEL-CMS-Forms-Module#26]
Hi team,

I use froms modun and create field select in CMS admin. But select display not working. (Please see picture attacht)
![select field display in browser](https://user-images.githubusercontent.com/4971199/210053057-a235cf5e-2eb1-4b39-8028-3be54e63f035.jpg)
![create field in CMS](https://user-images.githubusercontent.com/4971199/210053076-e32ff124-918c-4f69-a84c-e8dea3be2421.png)

Please help me.

**Comment by daylightstudio** [comment]
I've pushed a fix for this issue to the develop branch:
https://github.com/daylightstudio/FUEL-CMS-Forms-Module/commit/d1c7aac84b7dca9caadc1cc58a2cafd9ff02a580

**Comment by sontq** [comment]
> I've pushed a fix for this issue to the develop branch: [d1c7aac](https://github.com/daylightstudio/FUEL-CMS-Forms-Module/commit/d1c7aac84b7dca9caadc1cc58a2cafd9ff02a580)

I download lastest forms modun and I check lib already updated but have this proplem.

Please help me !

**Comment by daylightstudio** [comment]
Did you resave in the admin the form?

**Comment by sontq** [comment]
> Did you resave in the admin the form?

yes, i did
